language: node_js
node_js:
  - 'lts/*'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run clean
  - npm run build
  - npm run build:storybook
  - npm test
  - npm run test:coverage
on:
  branch: master
